services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: apps/server/postgres/Dockerfile
    restart: unless-stopped
    environment:
      # ${env_variable:-default_value}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-qualification}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-qualification}']
      interval: 30s
      timeout: 5s
      retries: 3
    
  redis:
    container_name: redis
    image: redis:8.6-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy volatile-ttl
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s       
      timeout: 5s
      retries: 3

  redis-insight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    ports:
     - '5040:5040'
    volumes:
     - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy


  server:
    container_name: server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - '${SERVER_PORT:-4000}:4000'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-qualification}
    healthcheck:
      # wget и curl недоступны внутри node:alpine
      test: ['CMD', 'node', '-e', "fetch('http://localhost:4000/health').then(r=>{if(!r.ok)throw r}).catch(()=>process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build:
        context: .
        dockerfile: apps/client/Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
        # СLIENT_PORT снаружи - 80 внутри nginx
        - '${CLIENT_PORT:-80}:80'
    healthcheck:
      # healthcheck выполняем по 80 порту, так как эти команды выполняются внутри докера, 
      # а внутри докера у нас клиент на 80-м порту
      # wget выдаёт: 
      # wget: can't connect to remote host: Connection refused
      # меняем на curl
      test: ['CMD-SHELL', 'curl -f http://localhost:80/ || exit 1']
      interval: 15s
      timeout: 5s
      retries: 3
    depends_on:
        server:
          condition: service_healthy

volumes:
  redis_data:
  redisinsight_data:
