packages:
  - 'apps/node/*'
  - 'packages/node/*'
allowBuilds:
  argon2: true
  lefthook: true

linkWorkspacePackages: true

catalogs:
  postgres:
    pg: ^8.20.0
    "@types/pg": ^8.18.0
  backend:
    redis: ^5.11.0
    zod: ^4.3.6
  devtools:
    dotenv: ^17.3.1
    dotenv-cli: ^11.0.0
    tsup: ^8.5.1
    tsx: ^4.21.0
