apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: "ghcr.io/neoplasmes/qualification_work/apps_node_server:custom"
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: app-env-config
            - secretRef:
                name: app-secret
          
