import type { ActionEffect, ActionParameterType, ActionRun } from '@/entities/action';

export type ActionParameterDraft = {
    id: string;
    key: string;
    label: string;
    type: ActionParameterType;
    required: boolean;
    defaultValue: string;
    keyAutoGenerated: boolean;
};

export type ActionValueMappingDraft = {
    id: string;
    columnKey: string;
    sourceKind: 'parameter' | 'literal';
    parameterKey: string;
    literalValue: string;
};

export type ActionEffectDraft = {
    id: string;
    kind: ActionEffect['kind'];
    datasetId: string;
    matchColumnKey: string;
    matchParameterKey: string;
    maxRows: string;
    values: ActionValueMappingDraft[];
};

export type ActionDraft = {
    id: string | null;
    name: string;
    description: string | null;
    parameters: ActionParameterDraft[];
    effects: ActionEffectDraft[];
};

export type ActionListFilters = {
    searchText: string;
    datasetIds: string[];
    effectKinds: Array<ActionEffect['kind']>;
    runStatuses: Array<ActionRun['status']>;
    runs: ActionRun[];
};
export {
    actionToDraft,
    coerceRunValues,
    createBlankActionDraft,
    createBlankEffectDraft,
    createBlankParameterDraft,
    createBlankValueMappingDraft,
    draftToActionPayload,
    filterActions,
    getDefaultRunValues,
    labelToKey,
} from '../lib';
