import type {
    Action,
    ActionDefinitionPayload,
    ActionEffect,
    ActionParameter,
    ActionParameterType,
    ActionRun,
} from '@/features/actions';

export type ActionParameterDraft = {
    id: string;
    key: string;
    label: string;
    type: ActionParameterType;
    required: boolean;
    defaultValue: string;
    keyAutoGenerated: boolean;
};

export const labelToKey = (label: string): string =>
    label.trim().toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');

export type ActionValueMappingDraft = {
    id: string;
    columnKey: string;
    sourceKind: 'parameter' | 'literal';
    parameterKey: string;
    literalValue: string;
};

export type ActionEffectDraft = {
    id: string;
    kind: ActionEffect['kind'];
    datasetId: string;
    matchColumnKey: string;
    matchParameterKey: string;
    maxRows: string;
    values: ActionValueMappingDraft[];
};

export type ActionDraft = {
    id: string | null;
    name: string;
    parameters: ActionParameterDraft[];
    effects: ActionEffectDraft[];
};

export type ActionListFilters = {
    searchText: string;
    datasetIds: string[];
    effectKinds: Array<ActionEffect['kind']>;
    runStatuses: Array<ActionRun['status']>;
    runs: ActionRun[];
};

let draftCounter = 0;

export const createDraftId = () => {
    draftCounter += 1;

    return `draft-${draftCounter}`;
};

const valueToDraftString = (value: unknown) => {
    if (value === undefined || value === null) {
        return '';
    }

    if (typeof value === 'string') {
        return value;
    }

    return JSON.stringify(value);
};

const parseDraftValue = (type: ActionParameterType, value: string): unknown => {
    const trimmed = value.trim();

    if (trimmed === '') {
        return undefined;
    }

    if (type === 'number') {
        const numberValue = Number(trimmed);
        if (!Number.isFinite(numberValue)) {
            throw new Error(`Default value for ${type} parameter must be a number.`);
        }

        return numberValue;
    }

    if (type === 'bool') {
        return trimmed === 'true';
    }

    return trimmed;
};

const parseLiteralValue = (value: string) => {
    const trimmed = value.trim();
    if (!trimmed) {
        return '';
    }

    try {
        return JSON.parse(trimmed) as unknown;
    } catch {
        return value;
    }
};

const valuesMapToDraft = (
    values: ActionEffect['values']
): ActionValueMappingDraft[] =>
    Object.entries(values).map(([columnKey, source]) => ({
        id: createDraftId(),
        columnKey,
        sourceKind: source.kind,
        parameterKey: source.kind === 'parameter' ? source.key : '',
        literalValue: source.kind === 'literal' ? valueToDraftString(source.value) : '',
    }));

const draftValuesToMap = (values: ActionValueMappingDraft[]) =>
    values.reduce<ActionEffect['values']>((acc, value) => {
        const columnKey = value.columnKey.trim();
        if (!columnKey) {
            return acc;
        }

        if (value.sourceKind === 'parameter') {
            acc[columnKey] = { kind: 'parameter', key: value.parameterKey };
        } else {
            acc[columnKey] = { kind: 'literal', value: parseLiteralValue(value.literalValue) };
        }

        return acc;
    }, {});

export const createBlankParameterDraft = (): ActionParameterDraft => ({
    id: createDraftId(),
    key: '',
    label: '',
    type: 'string',
    required: true,
    defaultValue: '',
    keyAutoGenerated: true,
});

export const createBlankValueMappingDraft = (): ActionValueMappingDraft => ({
    id: createDraftId(),
    columnKey: '',
    sourceKind: 'parameter',
    parameterKey: '',
    literalValue: '',
});

export const createBlankEffectDraft = (): ActionEffectDraft => ({
    id: createDraftId(),
    kind: 'insertRow',
    datasetId: '',
    matchColumnKey: '',
    matchParameterKey: '',
    maxRows: '1',
    values: [createBlankValueMappingDraft()],
});

export const createBlankActionDraft = (): ActionDraft => ({
    id: null,
    name: '',
    parameters: [createBlankParameterDraft()],
    effects: [createBlankEffectDraft()],
});

export const actionToDraft = (action: Action): ActionDraft => ({
    id: action.id,
    name: action.name,
    parameters: action.parameters.map(parameter => ({
        id: createDraftId(),
        key: parameter.key,
        label: parameter.label,
        type: parameter.type,
        required: parameter.required ?? false,
        defaultValue: valueToDraftString(parameter.defaultValue),
        keyAutoGenerated: false,
    })),
    effects: action.effects.map(effect => ({
        id: createDraftId(),
        kind: effect.kind,
        datasetId: effect.datasetId,
        matchColumnKey: effect.kind === 'updateRowsByMatch' ? effect.match.columnKey : '',
        matchParameterKey: effect.kind === 'updateRowsByMatch' ? effect.match.parameterKey : '',
        maxRows: effect.kind === 'updateRowsByMatch' ? String(effect.maxRows ?? 1) : '1',
        values: valuesMapToDraft(effect.values),
    })),
});

export const draftToActionPayload = (draft: ActionDraft): ActionDefinitionPayload => {
    const name = draft.name.trim();
    if (!name) {
        throw new Error('Action name can not be empty.');
    }

    const parameters: ActionParameter[] = draft.parameters
        .filter(parameter => parameter.key.trim() || parameter.label.trim())
        .map(parameter => {
            const key = parameter.key.trim();
            const label = parameter.label.trim();
            if (!key || !label) {
                throw new Error('Each parameter needs a key and label.');
            }

            const nextParameter: ActionParameter = {
                key,
                label,
                type: parameter.type,
                required: parameter.required,
            };
            const defaultValue = parseDraftValue(parameter.type, parameter.defaultValue);
            if (defaultValue !== undefined) {
                nextParameter.defaultValue = defaultValue;
            }

            return nextParameter;
        });

    const parameterKeys = new Set(parameters.map(parameter => parameter.key));
    if (parameterKeys.size !== parameters.length) {
        throw new Error('Parameter keys must be unique.');
    }

    const effects = draft.effects.map<ActionEffect>((effect, index) => {
        const datasetId = effect.datasetId.trim();
        const values = draftValuesToMap(effect.values);
        if (!datasetId) {
            throw new Error(`Effect ${index + 1} needs a dataset.`);
        }
        if (Object.keys(values).length === 0) {
            throw new Error(`Effect ${index + 1} needs at least one value mapping.`);
        }

        if (effect.kind === 'insertRow') {
            return {
                kind: 'insertRow',
                datasetId,
                values,
            };
        }

        if (!effect.matchColumnKey || !effect.matchParameterKey) {
            throw new Error(`Effect ${index + 1} needs a match column and parameter.`);
        }

        if (!parameterKeys.has(effect.matchParameterKey)) {
            throw new Error(`Effect ${index + 1} uses an unknown match parameter.`);
        }

        const maxRows = Number(effect.maxRows || 1);
        if (!Number.isInteger(maxRows) || maxRows < 1) {
            throw new Error(`Effect ${index + 1} max rows must be a positive integer.`);
        }

        return {
            kind: 'updateRowsByMatch',
            datasetId,
            match: {
                columnKey: effect.matchColumnKey,
                parameterKey: effect.matchParameterKey,
            },
            values,
            maxRows,
        };
    });

    if (effects.length === 0) {
        throw new Error('Action needs at least one effect.');
    }

    return {
        name,
        description: null,
        parameters,
        effects,
    };
};

export const getDefaultRunValues = (parameters: ActionParameter[]) =>
    parameters.reduce<Record<string, string>>((acc, parameter) => {
        acc[parameter.key] = valueToDraftString(parameter.defaultValue);

        return acc;
    }, {});

export const coerceRunValues = (
    parameters: ActionParameter[],
    values: Record<string, string>
) =>
    parameters.reduce<Record<string, unknown>>((acc, parameter) => {
        const raw = values[parameter.key] ?? '';
        const parsed = parseDraftValue(parameter.type, raw);
        if (parsed !== undefined || raw.trim() !== '') {
            acc[parameter.key] = parsed;
        }

        return acc;
    }, {});

export const filterActions = (actions: Action[], filters: ActionListFilters) => {
    const search = filters.searchText.trim().toLowerCase();
    const actionIdsByRunStatus =
        filters.runStatuses.length > 0
            ? new Set(
                  filters.runs
                      .filter(run => filters.runStatuses.includes(run.status))
                      .map(run => run.actionId)
              )
            : null;

    return actions.filter(action => {
        if (
            search &&
            !action.name.toLowerCase().includes(search) &&
            !(action.description ?? '').toLowerCase().includes(search)
        ) {
            return false;
        }

        if (
            filters.datasetIds.length > 0 &&
            !action.effects.some(effect => filters.datasetIds.includes(effect.datasetId))
        ) {
            return false;
        }

        if (
            filters.effectKinds.length > 0 &&
            !action.effects.some(effect => filters.effectKinds.includes(effect.kind))
        ) {
            return false;
        }

        if (actionIdsByRunStatus && !actionIdsByRunStatus.has(action.id)) {
            return false;
        }

        return true;
    });
};
