import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { useState } from 'react';
import { describe, expect, it } from 'vitest';

import type { DatasetMetadata } from '@/entities/dataset';

import { actionsTestIds } from '../../../const';
import { createBlankActionDraft, labelToKey } from '../../../lib';
import type {
    ActionDraft,
    ActionEffectDraft,
    ActionParameterDraft,
    ActionValueMappingDraft,
} from '../../../model';

import { ConfigureForm } from './ConfigureForm';

const dataset: DatasetMetadata = {
    dataset: {
        id: 'dataset-1',
        orgId: 'org-1',
        name: 'Invoices',
        sourceType: 'manual',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
    },
    columns: [
        {
            id: 'column-1',
            datasetId: 'dataset-1',
            key: 'status',
            displayName: 'Status',
            dataType: 'string',
            orderIndex: 0,
            isAnalyzable: true,
        },
    ],
    totalRows: 3,
};

const getByDataTestId = <T extends HTMLElement>(
    container: HTMLElement,
    testId: string
) => {
    const element = container.querySelector<T>(`[data-test-id="${testId}"]`);
    expect(element).not.toBeNull();

    return element as T;
};

const TestConfigureForm = () => {
    const [draft, setDraft] = useState<ActionDraft>(() => createBlankActionDraft());

    const updateParameter = (
        parameterId: string,
        patch: Partial<ActionParameterDraft>
    ) => {
        setDraft(current => ({
            ...current,
            parameters: current.parameters.map(parameter => {
                if (parameter.id !== parameterId) {
                    return parameter;
                }

                const next = { ...parameter, ...patch };
                if ('label' in patch && parameter.keyAutoGenerated) {
                    next.key = labelToKey(patch.label ?? '');
                }
                if ('key' in patch) {
                    next.keyAutoGenerated = false;
                }

                return next;
            }),
        }));
    };

    const updateEffect = (effectId: string, patch: Partial<ActionEffectDraft>) => {
        setDraft(current => ({
            ...current,
            effects: current.effects.map(effect =>
                effect.id === effectId ? { ...effect, ...patch } : effect
            ),
        }));
    };

    const updateMapping = (
        effectId: string,
        mappingId: string,
        patch: Partial<ActionValueMappingDraft>
    ) => {
        setDraft(current => ({
            ...current,
            effects: current.effects.map(effect =>
                effect.id === effectId
                    ? {
                          ...effect,
                          values: effect.values.map(mapping =>
                              mapping.id === mappingId
                                  ? { ...mapping, ...patch }
                                  : mapping
                          ),
                      }
                    : effect
            ),
        }));
    };

    return (
        <ConfigureForm
            draft={draft}
            datasets={[dataset]}
            disabled={false}
            formId="test-configure-form"
            onSubmit={event => event.preventDefault()}
            onDraftChange={setDraft}
            onUpdateParameter={updateParameter}
            onUpdateEffect={updateEffect}
            onUpdateMapping={updateMapping}
        />
    );
};

describe('ConfigureForm', () => {
    it('updates central parameter inputs and keeps generated key visible', async () => {
        const user = userEvent.setup();
        const { container } = render(<TestConfigureForm />);
        const labelInput = getByDataTestId<HTMLInputElement>(
            container,
            actionsTestIds.parameterLabelInput
        );
        const keyInput = getByDataTestId<HTMLInputElement>(
            container,
            actionsTestIds.parameterKeyInput
        );

        await user.type(labelInput, 'Сумма оплаты');

        expect(keyInput).toHaveValue('сумма_оплаты');

        await user.selectOptions(
            getByDataTestId<HTMLSelectElement>(
                container,
                actionsTestIds.parameterTypeSelect
            ),
            'number'
        );

        expect(
            getByDataTestId<HTMLSelectElement>(
                container,
                actionsTestIds.parameterTypeSelect
            )
        ).toHaveValue('number');
    });

    it('adds rows and switches a value mapping to literal mode', async () => {
        const user = userEvent.setup();
        const { container } = render(<TestConfigureForm />);

        await user.click(screen.getByRole('button', { name: /Add parameter/i }));
        await user.click(screen.getByRole('button', { name: /Add value/i }));
        await user.click(
            getByDataTestId(container, actionsTestIds.mappingSourceLiteralButton)
        );
        await user.type(
            getByDataTestId<HTMLInputElement>(
                container,
                actionsTestIds.mappingLiteralInput
            ),
            'paid'
        );

        expect(
            container.querySelectorAll(`[data-test-id="${actionsTestIds.parameterRow}"]`)
        ).toHaveLength(2);
        expect(
            container.querySelectorAll(`[data-test-id="${actionsTestIds.mappingRow}"]`)
        ).toHaveLength(2);
        expect(
            getByDataTestId<HTMLInputElement>(
                container,
                actionsTestIds.mappingLiteralInput
            )
        ).toHaveValue('paid');
    });
});
