; THIS is only for local development
[databases]
qualification = host=postgres port=5432 dbname=qualification

[pgbouncer]
listen_addr = *
listen_port = 5432
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
; In prod, there should be higher limit
max_client_conn = 1000
; Each pg connection - ~20mb of RAM. ~2.5GB peak at 100.
default_pool_size = 100
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits
