import { skipToken } from '@reduxjs/toolkit/query';
import { useCallback, useMemo, useState, type FormEvent } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { useActiveOrganization, useGetMeQuery } from '@/features/authenticate';
import {
    useCreateActionMutation,
    useExecuteActionMutation,
    usePatchActionMutation,
} from '@/features/manageActions';

import {
    useArchiveActionMutation,
    useListActionsQuery,
    type Action,
} from '@/entities/action';
import { useListDatasetsQuery } from '@/entities/dataset';

import { getApiErrorMessage } from '@/shared/api';
import { StatusMessage } from '@/shared/ui';

import { actionsTestIds } from '../const';
import {
    actionToDraft,
    canMutate,
    coerceRunValues,
    createBlankActionDraft,
    draftToActionPayload,
    getDefaultRunValues,
    getSelectedAction,
    labelToKey,
} from '../lib';
import {
    cancelCreateAction,
    selectAction,
    selectActionsWorkspaceTab,
    selectIsCreatingAction,
    selectSelectedActionId,
    setActionsWorkspaceTab,
    type ActionDraft,
    type ActionEffectDraft,
    type ActionParameterDraft,
    type ActionsWorkspaceTab,
    type ActionValueMappingDraft,
} from '../model';
import { ConfigureForm } from './components/ConfigureForm';
import { RunForm } from './components/RunForm';
import { WorkspaceHeader } from './components/WorkspaceHeader';
import { WorkspaceTabs } from './components/WorkspaceTabs';

import styles from './ActionsPage.module.scss';

export const ActionsWorkspace = () => {
    const selectedActionId = useSelector(selectSelectedActionId);
    const isCreatingAction = useSelector(selectIsCreatingAction);

    const meQuery = useGetMeQuery();
    const { activeOrg: org } = useActiveOrganization(meQuery.data);
    const actionsQuery = useListActionsQuery(org?.id ?? skipToken);

    const selectedAction = useMemo(
        () =>
            isCreatingAction
                ? undefined
                : getSelectedAction(actionsQuery.data, selectedActionId),
        [actionsQuery.data, isCreatingAction, selectedActionId]
    );

    if (!selectedAction && !isCreatingAction) {
        return (
            <section
                className={styles['workspace']}
                data-test-id={actionsTestIds.workspace}
                aria-label="Action details"
            >
                <p className={styles['placeholder']}>Select or create an action.</p>
            </section>
        );
    }

    // key drops local state on action switch instead of syncing via effect
    const editorKey = isCreatingAction ? '__new__' : (selectedAction?.id ?? '__none__');

    return (
        <ActionEditor
            key={editorKey}
            selectedAction={selectedAction}
            isCreatingAction={isCreatingAction}
            orgId={org?.id}
            orgRole={org?.role}
            refetchActions={actionsQuery.refetch}
        />
    );
};

type ActionEditorProps = {
    selectedAction: Action | undefined;
    isCreatingAction: boolean;
    orgId: string | undefined;
    orgRole: string | undefined;
    refetchActions: () => unknown;
};

const ActionEditor = ({
    selectedAction,
    isCreatingAction,
    orgId,
    orgRole,
    refetchActions,
}: ActionEditorProps) => {
    const dispatch = useDispatch();
    const workspaceTab = useSelector(selectActionsWorkspaceTab);

    const [draft, setDraft] = useState<ActionDraft>(() =>
        selectedAction ? actionToDraft(selectedAction) : createBlankActionDraft()
    );
    const [runValues, setRunValues] = useState<Record<string, string>>(() =>
        selectedAction ? getDefaultRunValues(selectedAction.parameters) : {}
    );
    const [error, setError] = useState('');
    const [lastRunMessage, setLastRunMessage] = useState('');
    const [archiveConfirmationId, setArchiveConfirmationId] = useState<string | null>(
        null
    );

    const datasetsQuery = useListDatasetsQuery(orgId ?? skipToken);

    const editable = canMutate(orgRole);

    const [createAction, createState] = useCreateActionMutation();
    const [patchAction, patchState] = usePatchActionMutation();
    const [archiveAction, archiveState] = useArchiveActionMutation();
    const [executeAction, executeState] = useExecuteActionMutation();

    const updateParameter = useCallback(
        (parameterId: string, patch: Partial<ActionParameterDraft>) => {
            setDraft(current => ({
                ...current,
                parameters: current.parameters.map(parameter => {
                    if (parameter.id !== parameterId) {
                        return parameter;
                    }

                    const next = { ...parameter, ...patch };
                    if ('label' in patch && parameter.keyAutoGenerated) {
                        next.key = labelToKey(patch.label ?? '');
                    }
                    if ('key' in patch) {
                        next.keyAutoGenerated = false;
                    }

                    return next;
                }),
            }));
        },
        []
    );

    const updateEffect = useCallback(
        (effectId: string, patch: Partial<ActionEffectDraft>) => {
            setDraft(current => ({
                ...current,
                effects: current.effects.map(effect =>
                    effect.id === effectId ? { ...effect, ...patch } : effect
                ),
            }));
        },
        []
    );

    const updateMapping = useCallback(
        (
            effectId: string,
            mappingId: string,
            patch: Partial<ActionValueMappingDraft>
        ) => {
            setDraft(current => ({
                ...current,
                effects: current.effects.map(effect =>
                    effect.id === effectId
                        ? {
                              ...effect,
                              values: effect.values.map(mapping =>
                                  mapping.id === mappingId
                                      ? { ...mapping, ...patch }
                                      : mapping
                              ),
                          }
                        : effect
                ),
            }));
        },
        []
    );

    const handleSave = useCallback(
        async (event: FormEvent<HTMLFormElement>) => {
            event.preventDefault();
            if (!orgId || !editable) {
                return;
            }

            try {
                setError('');
                const payload = draftToActionPayload(draft);
                if (isCreatingAction) {
                    const created = await createAction({
                        orgId,
                        ...payload,
                    }).unwrap();
                    dispatch(cancelCreateAction());
                    dispatch(selectAction(created.id));
                } else if (selectedAction) {
                    const saved = await patchAction({
                        actionId: selectedAction.id,
                        ...payload,
                    }).unwrap();
                    dispatch(selectAction(saved.id));
                }
                await refetchActions();
            } catch (saveError) {
                setError(
                    saveError instanceof Error
                        ? saveError.message
                        : getApiErrorMessage(saveError, 'Unable to save this action.')
                );
            }
        },
        [
            draft,
            orgId,
            editable,
            isCreatingAction,
            selectedAction,
            createAction,
            patchAction,
            dispatch,
            refetchActions,
        ]
    );

    const handleArchive = useCallback(async () => {
        if (!selectedAction || !editable) {
            return;
        }

        if (archiveConfirmationId !== selectedAction.id) {
            setArchiveConfirmationId(selectedAction.id);

            return;
        }

        try {
            setError('');
            await archiveAction(selectedAction.id).unwrap();
            dispatch(selectAction(null));
            setArchiveConfirmationId(null);
            await refetchActions();
        } catch (archiveError) {
            setError(getApiErrorMessage(archiveError, 'Unable to archive this action.'));
        }
    }, [
        selectedAction,
        editable,
        archiveConfirmationId,
        archiveAction,
        dispatch,
        refetchActions,
    ]);

    const handleRun = useCallback(
        async (event: FormEvent<HTMLFormElement>) => {
            event.preventDefault();
            if (!selectedAction || !editable) {
                return;
            }

            try {
                setError('');
                setLastRunMessage('');
                const parameters = coerceRunValues(selectedAction.parameters, runValues);
                const result = await executeAction({
                    actionId: selectedAction.id,
                    parameters,
                }).unwrap();
                setLastRunMessage(
                    result.status === 'success'
                        ? `Run completed with ${result.changes.length} changes.`
                        : (result.errorMessage ?? 'Run failed.')
                );
            } catch (runError) {
                setError(
                    runError instanceof Error
                        ? runError.message
                        : getApiErrorMessage(runError, 'Unable to run this action.')
                );
            }
        },
        [selectedAction, editable, runValues, executeAction]
    );

    const handleArchiveClick = useCallback(() => void handleArchive(), [handleArchive]);

    const handleRunValueChange = useCallback((key: string, value: string) => {
        setRunValues(current => ({ ...current, [key]: value }));
    }, []);

    const handleTabChange = useCallback(
        (tab: ActionsWorkspaceTab) => dispatch(setActionsWorkspaceTab(tab)),
        [dispatch]
    );

    const saving = createState.isLoading || patchState.isLoading;

    return (
        <section
            className={styles['workspace']}
            data-test-id={actionsTestIds.workspace}
            aria-label="Action details"
        >
            <WorkspaceHeader
                draft={draft}
                isCreatingAction={isCreatingAction}
                selectedActionName={selectedAction?.name}
                selectedActionId={selectedAction?.id}
                archiveConfirmationId={archiveConfirmationId}
                archiveDisabled={!editable || archiveState.isLoading}
                editable={editable}
                onArchive={handleArchiveClick}
            />

            <WorkspaceTabs
                activeTab={workspaceTab}
                runDisabled={isCreatingAction}
                onChange={handleTabChange}
            />

            {error ? <StatusMessage tone="error">{error}</StatusMessage> : null}

            {!editable && (
                <StatusMessage>
                    Viewer role can inspect actions and history, but can not edit or run
                    them.
                </StatusMessage>
            )}

            {workspaceTab === 'configure' ? (
                <ConfigureForm
                    draft={draft}
                    datasets={datasetsQuery.data ?? []}
                    disabled={!editable || saving}
                    saving={saving}
                    onSubmit={handleSave}
                    onDraftChange={setDraft}
                    onUpdateParameter={updateParameter}
                    onUpdateEffect={updateEffect}
                    onUpdateMapping={updateMapping}
                />
            ) : (
                <RunForm
                    action={selectedAction}
                    runValues={runValues}
                    disabled={!editable || executeState.isLoading}
                    lastRunMessage={lastRunMessage}
                    onRunValueChange={handleRunValueChange}
                    onSubmit={handleRun}
                />
            )}
        </section>
    );
};
