import { skipToken } from '@reduxjs/toolkit/query';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { useActiveOrganization, useGetMeQuery } from '@/features/authenticate';
import {
    useCreateActionMutation,
    useExecuteActionMutation,
    usePatchActionMutation,
} from '@/features/manageActions';

import { useArchiveActionMutation, useListActionsQuery } from '@/entities/action';
import { useListDatasetsQuery } from '@/entities/dataset';

import { getApiErrorMessage } from '@/shared/api';

import { actionsTestIds } from '../const';
import {
    actionToDraft,
    canMutate,
    coerceRunValues,
    createBlankActionDraft,
    draftToActionPayload,
    getDefaultRunValues,
    getSelectedAction,
    labelToKey,
} from '../lib';
import {
    cancelCreateAction,
    selectAction,
    selectActionsWorkspaceTab,
    selectIsCreatingAction,
    selectSelectedActionId,
    setActionsWorkspaceTab,
    type ActionDraft,
    type ActionEffectDraft,
    type ActionParameterDraft,
    type ActionValueMappingDraft,
} from '../model';
import { ConfigureForm } from './components/ConfigureForm';
import { RunForm } from './components/RunForm';
import { WorkspaceHeader } from './components/WorkspaceHeader';
import { WorkspaceTabs } from './components/WorkspaceTabs';

import styles from './ActionsPage.module.scss';

export const ActionsWorkspace = () => {
    const dispatch = useDispatch();
    const [draft, setDraft] = useState<ActionDraft>(() => createBlankActionDraft());
    const [draftSourceId, setDraftSourceId] = useState<string | null>(null);
    const [runValues, setRunValues] = useState<Record<string, string>>({});
    const [error, setError] = useState('');
    const [lastRunMessage, setLastRunMessage] = useState('');
    const [archiveConfirmationId, setArchiveConfirmationId] = useState<string | null>(
        null
    );

    const workspaceTab = useSelector(selectActionsWorkspaceTab);
    const selectedActionId = useSelector(selectSelectedActionId);
    const isCreatingAction = useSelector(selectIsCreatingAction);

    const meQuery = useGetMeQuery();
    const { activeOrg: org } = useActiveOrganization(meQuery.data);
    const actionsQuery = useListActionsQuery(org?.id ?? skipToken);
    const datasetsQuery = useListDatasetsQuery(org?.id ?? skipToken);

    const selectedAction = useMemo(
        () =>
            isCreatingAction
                ? undefined
                : getSelectedAction(actionsQuery.data, selectedActionId),
        [actionsQuery.data, isCreatingAction, selectedActionId]
    );
    const editable = canMutate(org?.role);

    const [createAction, createState] = useCreateActionMutation();
    const [patchAction, patchState] = usePatchActionMutation();
    const [archiveAction, archiveState] = useArchiveActionMutation();
    const [executeAction, executeState] = useExecuteActionMutation();

    useEffect(() => {
        if (isCreatingAction) {
            if (draftSourceId !== 'new') {
                setDraft(createBlankActionDraft());
                setDraftSourceId('new');
                setRunValues({});
                setError('');
                setLastRunMessage('');
            }

            return;
        }

        if (!selectedAction) {
            setDraftSourceId(null);
            setDraft(createBlankActionDraft());
            setRunValues({});

            return;
        }

        if (draftSourceId === selectedAction.id) {
            return;
        }

        setDraft(actionToDraft(selectedAction));
        setDraftSourceId(selectedAction.id);
        setRunValues(getDefaultRunValues(selectedAction.parameters));
        setError('');
        setLastRunMessage('');
        setArchiveConfirmationId(null);
    }, [draftSourceId, isCreatingAction, selectedAction]);

    const updateParameter = (
        parameterId: string,
        patch: Partial<ActionParameterDraft>
    ) => {
        setDraft(current => ({
            ...current,
            parameters: current.parameters.map(parameter => {
                if (parameter.id !== parameterId) {
                    return parameter;
                }

                const next = { ...parameter, ...patch };
                if ('label' in patch && parameter.keyAutoGenerated) {
                    next.key = labelToKey(patch.label ?? '');
                }
                if ('key' in patch) {
                    next.keyAutoGenerated = false;
                }

                return next;
            }),
        }));
    };

    const updateEffect = (effectId: string, patch: Partial<ActionEffectDraft>) => {
        setDraft(current => ({
            ...current,
            effects: current.effects.map(effect =>
                effect.id === effectId ? { ...effect, ...patch } : effect
            ),
        }));
    };

    const updateMapping = (
        effectId: string,
        mappingId: string,
        patch: Partial<ActionValueMappingDraft>
    ) => {
        setDraft(current => ({
            ...current,
            effects: current.effects.map(effect =>
                effect.id === effectId
                    ? {
                          ...effect,
                          values: effect.values.map(mapping =>
                              mapping.id === mappingId
                                  ? { ...mapping, ...patch }
                                  : mapping
                          ),
                      }
                    : effect
            ),
        }));
    };

    const handleSave = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!org || !editable) {
            return;
        }

        try {
            setError('');
            const payload = draftToActionPayload(draft);
            if (isCreatingAction) {
                const created = await createAction({
                    orgId: org.id,
                    ...payload,
                }).unwrap();
                dispatch(cancelCreateAction());
                dispatch(selectAction(created.id));
                setDraftSourceId(null);
            } else if (selectedAction) {
                const saved = await patchAction({
                    actionId: selectedAction.id,
                    ...payload,
                }).unwrap();
                dispatch(selectAction(saved.id));
                setDraftSourceId(null);
            }
            await actionsQuery.refetch();
        } catch (saveError) {
            setError(
                saveError instanceof Error
                    ? saveError.message
                    : getApiErrorMessage(saveError, 'Unable to save this action.')
            );
        }
    };

    const handleArchive = async () => {
        if (!selectedAction || !editable) {
            return;
        }

        if (archiveConfirmationId !== selectedAction.id) {
            setArchiveConfirmationId(selectedAction.id);

            return;
        }

        try {
            setError('');
            await archiveAction(selectedAction.id).unwrap();
            dispatch(selectAction(null));
            setArchiveConfirmationId(null);
            await actionsQuery.refetch();
        } catch (archiveError) {
            setError(getApiErrorMessage(archiveError, 'Unable to archive this action.'));
        }
    };

    const handleRun = async (event: FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        if (!selectedAction || !editable) {
            return;
        }

        try {
            setError('');
            setLastRunMessage('');
            const parameters = coerceRunValues(selectedAction.parameters, runValues);
            const result = await executeAction({
                actionId: selectedAction.id,
                parameters,
            }).unwrap();
            setLastRunMessage(
                result.status === 'success'
                    ? `Run completed with ${result.changes.length} changes.`
                    : (result.errorMessage ?? 'Run failed.')
            );
        } catch (runError) {
            setError(
                runError instanceof Error
                    ? runError.message
                    : getApiErrorMessage(runError, 'Unable to run this action.')
            );
        }
    };

    if (!selectedAction && !isCreatingAction) {
        return (
            <section className={styles['workspace']} aria-label="Action details">
                <p className={styles['placeholder']}>Select or create an action.</p>
            </section>
        );
    }

    return (
        <section
            className={styles['workspace']}
            data-test-id={actionsTestIds.workspace}
            aria-label="Action details"
        >
            <WorkspaceHeader
                draft={draft}
                isCreatingAction={isCreatingAction}
                selectedActionName={selectedAction?.name}
                selectedActionId={selectedAction?.id}
                archiveConfirmationId={archiveConfirmationId}
                archiveDisabled={!editable || archiveState.isLoading}
                editable={editable}
                onArchive={() => void handleArchive()}
            />

            <WorkspaceTabs
                activeTab={workspaceTab}
                runDisabled={isCreatingAction}
                onChange={tab => dispatch(setActionsWorkspaceTab(tab))}
            />

            {error && (
                <div role="alert" className={`${styles['status']} ${styles['error']}`}>
                    {error}
                </div>
            )}

            {!editable && (
                <div className={styles['status']}>
                    Viewer role can inspect actions and history, but can not edit or run
                    them.
                </div>
            )}

            {workspaceTab === 'configure' ? (
                <ConfigureForm
                    draft={draft}
                    datasets={datasetsQuery.data ?? []}
                    disabled={!editable || createState.isLoading || patchState.isLoading}
                    saving={createState.isLoading || patchState.isLoading}
                    onSubmit={handleSave}
                    onDraftChange={setDraft}
                    onUpdateParameter={updateParameter}
                    onUpdateEffect={updateEffect}
                    onUpdateMapping={updateMapping}
                />
            ) : (
                <RunForm
                    action={selectedAction}
                    runValues={runValues}
                    disabled={!editable || executeState.isLoading}
                    lastRunMessage={lastRunMessage}
                    onRunValueChange={(key, value) =>
                        setRunValues(current => ({ ...current, [key]: value }))
                    }
                    onSubmit={handleRun}
                />
            )}
        </section>
    );
};
