apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-config
  namespace: app
data:
  #* THIS DATA SHOULD BE COHERENT WITH postgres and redis values.yaml
  POSTGRES_HOST: "postgres-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "qualification"

  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  
  SERVER_PORT: "3000"
  CLIENT_PORT: "3001"

