apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - client
  - server
  - data-service
  - auth
  - gateway
