apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123"
  REDIS_PASSWORD: "123"
  # db url is optional actually
  DATABASE_URL: ""
  # additional key for secure passwords encryption
  PEPPER: "asdfsdkfsdlfjslkdfjsldkfjlskdjf"