apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123"
  REDIS_PASSWORD: "123"
  # full connection string used by node and go services
  DATABASE_URL: "postgres://admin:123@postgres-postgresql:5432/qualification?sslmode=disable"
  # pepper used by auth for password hashing
  AUTH_PEPPER: "asdfsdkfsdlfjslkdfjsldkfjlskdjf"
