import type { ActionDefinitionPayload } from '@/features/manageActions';

import type { Action, ActionEffect, ActionParameter } from '@/entities/action';

import type { ActionDraft, ActionValueMappingDraft } from '../model';
import { createDraftId } from './draftIds';
import {
    draftValuesToMap,
    parseDraftValue,
    parseLiteralValue,
    valueToDraftString,
} from './draftValues';

const valuesMapToDraft = (values: ActionEffect['values']): ActionValueMappingDraft[] =>
    Object.entries(values).map(([columnKey, source]) => ({
        id: createDraftId(),
        columnKey,
        sourceKind: source.kind,
        parameterKey: source.kind === 'parameter' ? source.key : '',
        literalValue: source.kind === 'literal' ? valueToDraftString(source.value) : '',
        operation: source.kind === 'computed' ? '=' : (source.operation ?? '='),
        leftParameterKey: source.kind === 'computed' ? source.leftParameterKey : '',
        computedOperation: source.kind === 'computed' ? source.operation : '*',
        rightParameterKey: source.kind === 'computed' ? source.rightParameterKey : '',
    }));

const getMatchSourceKind = (effect: ActionEffect) => {
    if (effect.kind !== 'updateRowsByMatch') {
        return 'parameter';
    }

    return effect.match.source?.kind ?? 'parameter';
};

export const actionToDraft = (action: Action): ActionDraft => ({
    id: action.id,
    name: action.name,
    description: action.description ?? null,
    parameters: action.parameters.map(parameter => ({
        id: createDraftId(),
        key: parameter.key,
        label: parameter.label,
        type: parameter.type,
        required: parameter.required ?? false,
        defaultValue: valueToDraftString(parameter.defaultValue),
        hidden: parameter.hidden ?? false,
        keyAutoGenerated: false,
    })),
    effects: action.effects.map(effect => ({
        id: createDraftId(),
        kind: effect.kind,
        datasetId: effect.datasetId,
        matchColumnKey: effect.kind === 'updateRowsByMatch' ? effect.match.columnKey : '',
        matchSourceKind: getMatchSourceKind(effect),
        matchParameterKey:
            effect.kind === 'updateRowsByMatch'
                ? effect.match.source?.kind === 'parameter'
                    ? effect.match.source.key
                    : (effect.match.parameterKey ?? '')
                : '',
        matchLiteralValue:
            effect.kind === 'updateRowsByMatch' && effect.match.source?.kind === 'literal'
                ? valueToDraftString(effect.match.source.value)
                : '',
        maxRows: effect.kind === 'updateRowsByMatch' ? String(effect.maxRows ?? 1) : '1',
        values: valuesMapToDraft(effect.values),
    })),
});

export const draftToActionPayload = (draft: ActionDraft): ActionDefinitionPayload => {
    const name = draft.name.trim();
    if (!name) {
        throw new Error('Action name can not be empty.');
    }

    const parameters = getPayloadParameters(draft);
    const parameterKeys = new Set(parameters.map(parameter => parameter.key));
    if (parameterKeys.size !== parameters.length) {
        throw new Error('Parameter keys must be unique.');
    }

    const effects = getPayloadEffects(draft, parameterKeys);
    if (effects.length === 0) {
        throw new Error('Action needs at least one effect.');
    }

    return {
        name,
        description: draft.description,
        parameters,
        effects,
    };
};

const getPayloadParameters = (draft: ActionDraft): ActionParameter[] =>
    draft.parameters
        .filter(parameter => parameter.key.trim() || parameter.label.trim())
        .map(parameter => {
            const key = parameter.key.trim();
            const label = parameter.label.trim();
            if (!key || !label) {
                throw new Error('Each parameter needs a key and label.');
            }

            const nextParameter: ActionParameter = {
                key,
                label,
                type: parameter.type,
                required: parameter.required,
            };
            if (parameter.hidden) {
                nextParameter.hidden = true;
            }
            const defaultValue = parseDraftValue(parameter.type, parameter.defaultValue);
            if (defaultValue !== undefined) {
                nextParameter.defaultValue = defaultValue;
            }

            return nextParameter;
        });

const getPayloadEffects = (
    draft: ActionDraft,
    parameterKeys: Set<string>
): ActionEffect[] =>
    draft.effects.map<ActionEffect>((effect, index) => {
        const datasetId = effect.datasetId.trim();
        const values = draftValuesToMap(effect.values, effect.kind);
        if (!datasetId) {
            throw new Error(`Effect ${index + 1} needs a dataset.`);
        }
        if (Object.keys(values).length === 0) {
            throw new Error(`Effect ${index + 1} needs at least one value mapping.`);
        }
        assertValueSourcesKnown(values, parameterKeys, index);

        if (effect.kind === 'insertRow') {
            return { kind: 'insertRow', datasetId, values };
        }

        return getUpdateRowsEffect(effect, index, datasetId, values, parameterKeys);
    });

const getUpdateRowsEffect = (
    effect: ActionDraft['effects'][number],
    index: number,
    datasetId: string,
    values: ActionEffect['values'],
    parameterKeys: Set<string>
): ActionEffect => {
    if (!effect.matchColumnKey) {
        throw new Error(`Effect ${index + 1} needs a match column.`);
    }

    if (effect.matchSourceKind === 'parameter') {
        if (!effect.matchParameterKey || !parameterKeys.has(effect.matchParameterKey)) {
            throw new Error(`Effect ${index + 1} uses an unknown match parameter.`);
        }
    }

    const maxRows = Number(effect.maxRows || 1);
    if (!Number.isInteger(maxRows) || maxRows < 1) {
        throw new Error(`Effect ${index + 1} max rows must be a positive integer.`);
    }

    return {
        kind: 'updateRowsByMatch',
        datasetId,
        match: {
            columnKey: effect.matchColumnKey,
            source:
                effect.matchSourceKind === 'literal'
                    ? {
                          kind: 'literal',
                          value: parseLiteralValue(effect.matchLiteralValue),
                      }
                    : {
                          kind: 'parameter',
                          key: effect.matchParameterKey,
                      },
        },
        values,
        maxRows,
    };
};

const assertValueSourcesKnown = (
    values: ActionEffect['values'],
    parameterKeys: Set<string>,
    index: number
) => {
    for (const source of Object.values(values)) {
        if (source.kind === 'parameter') {
            if (!source.key || !parameterKeys.has(source.key)) {
                throw new Error(`Effect ${index + 1} uses an unknown value parameter.`);
            }
        } else if (
            source.kind === 'computed' &&
            (!parameterKeys.has(source.leftParameterKey) ||
                !parameterKeys.has(source.rightParameterKey))
        ) {
            throw new Error(`Effect ${index + 1} uses an unknown computed parameter.`);
        }
    }
};
