import type {
    ActionDraft,
    ActionEffectDraft,
    ActionParameterDraft,
    ActionValueMappingDraft,
} from '../model';
import { createDraftId } from './draftIds';

export const createBlankParameterDraft = (): ActionParameterDraft => ({
    id: createDraftId(),
    key: '',
    label: '',
    type: 'string',
    required: true,
    defaultValue: '',
    hidden: false,
    keyAutoGenerated: true,
});

export const createBlankValueMappingDraft = (): ActionValueMappingDraft => ({
    id: createDraftId(),
    columnKey: '',
    sourceKind: 'parameter',
    parameterKey: '',
    literalValue: '',
    operation: '=',
    leftParameterKey: '',
    computedOperation: '*',
    rightParameterKey: '',
});

export const createBlankEffectDraft = (): ActionEffectDraft => ({
    id: createDraftId(),
    kind: 'insertRow',
    datasetId: '',
    matchColumnKey: '',
    matchSourceKind: 'parameter',
    matchParameterKey: '',
    matchLiteralValue: '',
    maxRows: '1',
    values: [createBlankValueMappingDraft()],
});

export const createBlankActionDraft = (): ActionDraft => ({
    id: null,
    name: '',
    description: null,
    parameters: [createBlankParameterDraft()],
    effects: [createBlankEffectDraft()],
});
