import { useCallback, type Dispatch, type SetStateAction } from 'react';

import { labelToKey } from '../../../../lib';
import {
    type ActionDraft,
    type ActionEffectDraft,
    type ActionParameterDraft,
    type ActionValueMappingDraft,
} from '../../../../model';

export const useActionDraftUpdaters = (
    setDraft: Dispatch<SetStateAction<ActionDraft>>
) => {
    const updateParameter = useCallback(
        (parameterId: string, patch: Partial<ActionParameterDraft>) => {
            setDraft(current => ({
                ...current,
                parameters: current.parameters.map(parameter => {
                    if (parameter.id !== parameterId) {
                        return parameter;
                    }

                    const next = { ...parameter, ...patch };
                    if ('label' in patch && parameter.keyAutoGenerated) {
                        next.key = labelToKey(patch.label ?? '');
                    }
                    if ('key' in patch) {
                        next.keyAutoGenerated = false;
                    }

                    return next;
                }),
            }));
        },
        [setDraft]
    );

    const updateEffect = useCallback(
        (effectId: string, patch: Partial<ActionEffectDraft>) => {
            setDraft(current => ({
                ...current,
                effects: current.effects.map(effect =>
                    effect.id === effectId ? { ...effect, ...patch } : effect
                ),
            }));
        },
        [setDraft]
    );

    const updateMapping = useCallback(
        (
            effectId: string,
            mappingId: string,
            patch: Partial<ActionValueMappingDraft>
        ) => {
            setDraft(current => ({
                ...current,
                effects: current.effects.map(effect =>
                    effect.id === effectId
                        ? {
                              ...effect,
                              values: effect.values.map(mapping =>
                                  mapping.id === mappingId
                                      ? { ...mapping, ...patch }
                                      : mapping
                              ),
                          }
                        : effect
                ),
            }));
        },
        [setDraft]
    );

    return { updateEffect, updateMapping, updateParameter };
};
