export const chartsTestIds = {
    listPanel: 'charts-list-panel',
    createChartButton: 'charts-create-chart-button',
    chartListItem: 'charts-list-item',
    filterPanel: 'charts-filter-panel',
    filterTabDatasets: 'charts-filter-tab-datasets',
    filterTabDashboards: 'charts-filter-tab-dashboards',
    filterChip: 'charts-filter-chip',
    clearFilterButton: 'charts-clear-filter-button',
    workspace: 'charts-workspace',
    changeDatasetButton: 'charts-change-dataset-button',
    editButton: 'charts-edit-button',
    refreshDataButton: 'charts-refresh-data-button',
    deleteButton: 'charts-delete-button',
    cancelEditButton: 'charts-cancel-edit-button',
    createChartModal: 'charts-create-chart-modal',
    modalDatasetItem: 'charts-modal-dataset-item',
    modalCloseButton: 'charts-modal-close-button',
} as const;
